In [33]:
import pandas as pd
import seaborn as sns
import numpy as np
from datetime import date, timedelta

In [34]:
def find_sheet_name(sheet_names):
    filtered_sheet_names = list(
        filter(
            lambda x: (
                "vdt" in x.lower()
                or "vđt" in x.lower()
                or "von" in x.lower()
                or "vnsnn" in x.lower()
            )
            and "nsnn" in x.lower()
            and ("quý" not in x.lower())
            and ("quy" not in x.lower())
            and ("txh" not in x.lower()),
            sheet_names,
        )
    )

    if len(filtered_sheet_names) == 1:
        return filtered_sheet_names[0]

    filtered_sheet_names = list(
        filter(
            lambda x: (
                "vdt" in x.lower()
                or "vđt" in x.lower()
                or "von" in x.lower()
                or "vnsnn" in x.lower()
            )
            and "thực hiện" in x.lower()
            and ("quý" not in x.lower())
            and ("quy" not in x.lower())
            and ("txh" not in x.lower()),
            sheet_names,
        )
    )

    if len(filtered_sheet_names) == 1:
        return filtered_sheet_names[0]

    filtered_sheet_names = list(
        filter(
            lambda x: (
                "vdt" in x.lower()
                or "vđt" in x.lower()
                or "von" in x.lower()
                or "vnsnn" in x.lower()
            )
            and ("quý" not in x.lower())
            and ("quy" not in x.lower())
            and ("txh" not in x.lower()),
            sheet_names,
        )
    )

    if len(filtered_sheet_names) == 1:
        return filtered_sheet_names[0]

    filtered_sheet_names = list(
        filter(
            lambda x: (
                "vdt" in x.lower()
                or "vđt" in x.lower()
                or "von" in x.lower()
                or "vnsnn" in x.lower()
                or "dtu" in x.lower()
            )
            and ("quý" not in x.lower())
            and ("quy" not in x.lower())
            and ("txh" not in x.lower()),
            sheet_names,
        )
    )

    if len(filtered_sheet_names) == 1:
        return filtered_sheet_names[0]

    if len(sheet_names) == 43:
        return "20"
    
    if len(sheet_names) == 13:
        return "Sheet1"

    raise RuntimeError(sheet_names, filtered_sheet_names)

In [35]:
en_to_vn = {
    "TOTAL": "TỔNG SỐ",
    "Central": "Trung ương",
    "Of which:": "Trong đó:",
    "Ministry of Transport": "Bộ Giao thông vận tải",
    "Ministry of Health": "Bộ Y tế",
    "Ministry of Agriculture & Rural Development": "Bộ NN và PTNT",
    "Ministry of Education & Training": "Bộ Giáo dục - Đào tạo",
    "Ministry of Natural Resources & Environment": "Bộ Tài nguyên và Môi trường",
    "Ministry of Culture, Sports & Tourism": "Bộ Văn hóa, Thể thao và Du lịch",
    "Ministry of Industry & Trade": "Bộ Công thương",
    "Ministry of Construction": "Bộ Xây dựng",
    "Ministry of Science & Technology": "Bộ Khoa học và Công nghệ",
    "Ministry of Information & Communications": "Bộ Thông tin và Truyền thông",
    "Local": "Địa phương",
    "Provincial level": "Vốn ngân sách NN cấp tỉnh",
    "District level": "Vốn ngân sách NN cấp huyện",
    "Commune level": "Vốn ngân sách NN cấp xã",
    "Selected localities": "Phân theo một số tỉnh, thành phố",
    "Ha Noi": "Hà Nội",
    "Ho Chi Minh city": "TP. Hồ Chí Minh",
    "Quang Ninh": "Quảng Ninh",
    "Binh Duong": "Bình Dương",
    "Hai Phong": "Hải Phòng",
    "Thanh Hoa": "Thanh Hóa",
    "Ba Ria - Vung Tau": "Bà Rịa - Vũng Tàu",
    "Nghe An": "Nghệ An",
    "Binh Dinh": "Bình Định",
    "Vinh Phuc": "Vĩnh Phúc",
    "Bac Ninh": "Bắc Ninh",
    "Dong Nai": "Đồng Nai",
    "Quang Nam": "Quảng Nam",
    "Bac Giang": "Bắc Giang",
    "Quang Ngai": "Quảng Ngãi",
    "Tien Giang": "Tiền Giang",
    "Thue Thien - Hue": "Thừa Thiên - Huế",
    "Thai Nguyen": "Thái Nguyên",
    "Tay Ninh": "Tây Ninh",
    "Binh Thuan": "Bình Thuận",
    "Binh Phuoc": "Bình Phước",
    "Long An": "Long An",
    "Thua Thien - Hue": "Thừa Thiên - Huế",
    "Phu Yen": "Phú Yên",
    "An Giang": "An Giang",
    "Ha Tinh": "Hà Tĩnh",
    "Thai Binh": "Thái Bình",
    "Kien Giang": "Kiên Giang",
}

In [36]:
def get_vdt(xl, sheet_name, date):
    df = xl.parse(sheet_name)

    df = df.dropna(axis=1, how="all")

    df[df.columns[0]] = (
        df[df.columns[0]]
        .replace(r"\s+", " ", regex=True)
        .replace(r"\n", " ", regex=True)
        .str.strip()
    )
    df[df.columns[1]] = (
        df[df.columns[1]]
        .replace(r"\s+", " ", regex=True)
        .replace(r"\n", " ", regex=True)
        .str.strip()
    )

    if (
        len(
            df[df.columns[1]][
                (df[df.columns[1]] == "Trung ương") | (df[df.columns[1]] == "Central")
            ].index
        )
        > 0
    ):
        df[df.columns[1]] = df[df.columns[1]].fillna(df[df.columns[0]])
        df = df.drop(columns=[df.columns[0]])
    df = df.reset_index(drop=True)

    df = df.drop(
        list(
            range(
                df[df.columns[0]][
                    (df[df.columns[0]] == "TỔNG SỐ") | ((df[df.columns[0]] == "TOTAL"))
                ].index[0]
            )
        )
    )
    df = df.reset_index(drop=True)

    if len(df[df.columns[0]][df[df.columns[0]] == "TOTAL"].index) > 0:
        df[df.columns[0]] = df[df.columns[0]].map(en_to_vn)

    if len(df.columns) == 6:
        df.columns = [
            "Phân Loại",
            "Total-Pre-Month",
            "Total-M",
            "Total-YOY",
            "YOP",
            "YTD-YOY",
        ]

        df["YTD-YOY"] = df["YTD-YOY"] - 100
    elif len(df.columns) == 5 and int(date.split("-")[1]) == 1:
        df = df.drop(columns=df.columns[1])
        df.columns = ["Phân Loại", "Total-M", "YOP", "YTD-YOY"]
        df["Total-YOY"] = df["Total-M"]
        df["YTD-YOY"] = df["YTD-YOY"] - 100
        df['Total-Pre-Month'] = np.nan
    else:
        raise RuntimeError

    df = df[df["Total-M"].notna()].replace("-", None)
    df = df[df["Total-YOY"].notna()].replace("-", None)
    df = df[df["YOP"].notna()].replace("-", None)
    df = df[df["YTD-YOY"].notna()].replace("-", None)

    df["Total-Pre-Month"] = df["Total-Pre-Month"].astype(float)
    df["Total-M"] = df["Total-M"].astype(float)
    df["Total-YOY"] = df["Total-YOY"].astype(float)
    df["YOP"] = df["YOP"].astype(float)
    df["YTD-YOY"] = df["YTD-YOY"].astype(float)

    df["MOM"] = 100 * (df["Total-M"] / df["Total-Pre-Month"]) - 100

    df["Date"] = date
    df["Date"] = pd.to_datetime(df["Date"], dayfirst=False)

    df["Month"] = df["Date"].dt.strftime("%Y-%m")

    df["PreMonth"] = (
        df["Date"]
        .apply(
            lambda x: (
                x.replace(month=x.month - 1, day=1)
                if x.month > 1
                else x.replace(year=x.year - 1, month=12, day=1)
            )
        )
        .dt.strftime("%Y-%m")
    )

    df["PreYearMonth"] = (
        df["Date"]
        .apply(lambda x: x.replace(year=x.year - 1, day=1))
        .dt.strftime("%Y-%m")
    )

    return df


xl = pd.ExcelFile("../datas/2024-01-29-02-Bieu-T1-2024-1.xlsx")

get_vdt(xl, find_sheet_name(xl.sheet_names), "2024-01-29")

,Phân Loại,Total-M,YOP,YTD-YOY,Total-YOY,Total-Pre-Month,MOM,Date,Month,PreMonth,PreYearMonth
0,TỔNG SỐ,31118.628,4.425307,12.494573,31118.628,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
1,Trung ương,4662.100,3.957896,3.733157,4662.100,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
3,Bộ Giao thông vận tải,3040.410,5.095863,-5.177130,3040.410,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
4,Bộ NN và PTNT,305.620,3.015369,13.058597,305.620,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
5,Bộ Giáo dục và Đào tạo,42.720,2.834923,-4.258180,42.720,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
6,"Bộ Văn hóa, Thể thao và Du lịch",37.220,3.497594,-29.800075,37.220,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
7,Bộ Công Thương,35.320,3.339321,18.722689,35.320,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
8,Bộ Y tế,33.120,2.639633,-12.427287,33.120,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
9,Bộ Tài nguyên và Môi trường,27.920,2.501433,-8.519004,27.920,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
10,Bộ Xây dựng,15.940,4.917173,-26.237853,15.940,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
11,Bộ Thông tin và Truyền thông,13.840,3.050474,8.463950,13.840,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
12,Bộ Khoa học và Công nghệ,9.670,3.749806,5.914567,9.670,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
13,Địa phương,26456.528,4.519357,14.194184,26456.528,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
14,Vốn ngân sách NN cấp tỉnh,17388.024,4.166018,11.083340,17388.024,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
15,Vốn ngân sách NN cấp huyện,7892.160,5.325410,20.816311,7892.160,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
16,Vốn ngân sách NN cấp xã,1176.344,5.932471,19.727232,1176.344,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
18,Hà Nội,3856.891,4.955001,56.058704,3856.891,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
19,TP. Hồ Chí Minh,1530.690,2.057514,20.382692,1530.690,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
20,Quảng Ninh,1139.268,5.178491,42.179768,1139.268,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
21,Hải Phòng,1053.163,5.942627,3.486961,1053.163,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
22,Bà Rịa - Vũng Tàu,1009.364,5.066818,48.351671,1009.364,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
23,Hòa Bình,854.063,4.276143,12.928575,854.063,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
24,Đồng Nai,823.581,4.810505,6.937184,823.581,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
25,Bình Dương,669.257,4.454847,24.497180,669.257,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
26,Đắk Lắk,589.432,4.865041,11.786862,589.432,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
27,Nghệ An,567.080,6.823039,36.080149,567.080,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
28,Thanh Hóa,528.368,5.821166,2.063019,528.368,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
29,Nam Định,514.204,5.825105,11.744368,514.204,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
30,An Giang,464.162,5.968682,21.027120,464.162,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
31,Thái Bình,449.636,5.599983,4.980575,449.636,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
32,Ninh Bình,437.008,6.827824,-3.482943,437.008,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
33,Vĩnh Phúc,426.241,6.598257,-12.593381,426.241,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
34,Thái Nguyên,424.610,6.294398,57.598590,424.610,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
35,Bắc Giang,424.468,6.528593,19.206131,424.468,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
36,Phú Thọ,418.500,4.624624,3.167755,418.500,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
37,Quảng Nam,414.061,5.184664,9.468995,414.061,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
38,Hưng Yên,383.840,5.532680,53.015746,383.840,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01
39,Lào Cai,383.730,6.421370,10.180490,383.730,NaN,NaN,2024-01-29,2024-01,2023-12,2023-01

In [37]:
import os
import contextlib

dfs_vdt_origin = []
for file_name in sorted(
    os.listdir("../datas"),
    key=lambda filename: f"{filename.split('-')[0]}-{filename.split('-')[1]}-{filename.split('-')[2]}",
    reverse=True,
):
    if file_name.startswith(".~"):
        continue

    try:
        file_path = os.path.join("../datas", file_name)

        year = int(file_name.split("-")[0])
        month = int(file_name.split("-")[1])
        day = int(file_name.split("-")[2])

        if year < 2012:
            continue

        xl = pd.ExcelFile(file_path)

        df_xk = get_vdt(xl, find_sheet_name(xl.sheet_names), f"{year}-{month}-{day}")

        dfs_vdt_origin.append(df_xk)
    except Exception as e:
        print(file_name)
        raise e

In [38]:
dfs_vdt = pd.concat(dfs_vdt_origin, ignore_index=True, axis=0)
dfs_vdt["Date"] = pd.to_datetime(dfs_vdt["Date"], dayfirst=False)
dfs_vdt

,Phân Loại,Total-Pre-Month,Total-M,Total-YOY,YOP,YTD-YOY,MOM,Date,Month,PreMonth,PreYearMonth
0,TỔNG SỐ,79042.785,86378.37819,661294.16324,84.626662,3.309492,9.280535,2024-12-29,2024-12,2024-11,2023-12
1,Trung ương,12398.520,13826.52000,112804.14000,87.113914,-0.430428,11.517504,2024-12-29,2024-12,2024-11,2023-12
2,Bộ Giao thông vận tải,7689.130,8465.42000,70223.83000,93.053254,-15.246546,10.095941,2024-12-29,2024-12,2024-11,2023-12
3,Bộ NN và PTNT,1049.920,1246.82000,9854.06000,83.968604,21.993481,18.753810,2024-12-29,2024-12,2024-11,2023-12
4,Bộ Y tế,151.610,179.54000,1176.74000,58.874680,28.127960,18.422268,2024-12-29,2024-12,2024-11,2023-12
...,...,...,...,...,...,...,...,...,...,...,...
5737,Khánh Hoà,NaN,85.00000,85.00000,4.476276,-18.582375,NaN,2012-01-30,2012-01,2011-12,2011-01
5738,Hưng Yên,NaN,83.60000,83.60000,7.555355,6.091371,NaN,2012-01-30,2012-01,2011-12,2011-01
5739,Ninh Thuận,NaN,66.00000,66.00000,7.581850,3.125000,NaN,2012-01-30,2012-01,2011-12,2011-01
5740,Đắk Lắk,NaN,57.00000,57.00000,5.013634,-37.362637,NaN,2012-01-30,2012-01,2011-12,2011-01
5741,Sơn La,NaN,54.50000,54.50000,4.762321,-71.673597,NaN,2012-01-30,2012-01,2011-12,2011-01

In [39]:
convert_phan_loai = {
    "An Giang": "An Giang",
    "Bà Rịa - Vũng Tàu": "Bà Rịa - Vũng Tàu",
    "Bà Rịa-Vũng Tàu": "Bà Rịa - Vũng Tàu",
    "Bình Dương": "Bình Dương",
    "Bình Phước": "Bình Phước",
    "Bình Định": "Bình Định",
    "Bạc Liêu": "Bạc Liêu",
    "Bắc Giang": "Bắc Giang",
    "Bắc Ninh": "Bắc Ninh",
    "Bến Tre": "Bến Tre",
    "Bộ Công Thương": "Bộ Công Thương",
    "Bộ Công thương": "Bộ Công Thương",
    "Bộ Giao thông Vận tải": "Bộ Giao thông Vận tải",
    "Bộ Giao thông vận tải": "Bộ Giao thông Vận tải",
    "Bộ Giáo dục - Đào tạo": "Bộ Giáo dục - Đào tạo",
    "Bộ Giáo dục và Đào tạo": "Bộ Giáo dục - Đào tạo",
    "Bộ Khoa học và Công nghệ": "Bộ Khoa học và Công nghệ",
    "Bộ NN và PTNT": "Bộ NN và PTNT",
    "Bộ Thông tin và Truyền thông": "Bộ Thông tin và Truyền thông",
    "Bộ Tài nguyên và Môi trường": "Bộ Tài nguyên và Môi trường",
    "Bộ Văn hoá, Thể thao và Du lịch": "Bộ Văn hoá, Thể thao và Du lịch",
    "Bộ Văn hoá,Thể thao và Du lịch": "Bộ Văn hoá, Thể thao và Du lịch",
    "Bộ Văn hóa, Thể thao và Du lịch": "Bộ Văn hoá, Thể thao và Du lịch",
    "Bộ Xây dựng": "Bộ Xây dựng",
    "Bộ Y tế": "Bộ Y tế",
    "Cà Mau": "Cà Mau",
    "Cần Thơ": "Cần Thơ",
    "Hà Tĩnh": "Hà Tĩnh",
    "Hà Giang": "Hà Giang",
    "Hà Nam": "Hà Nam",
    "Hà Nội": "Hà Nội",
    "Hà Tĩnh": "Hà Tĩnh",
    "Hòa Bình": "Hòa Bình",
    "Hưng Yên": "Hưng Yên",
    "Hải Dương": "Hải Dương",
    "Hải Phòng": "Hải Phòng",
    "Hậu Giang": "Hậu Giang",
    "Khánh Hòa": "Khánh Hòa",
    "Khánh Hoà": "Khánh Hòa",
    "Khánh Hòa": "Khánh Hòa",
    "Kiên Giang": "Kiên Giang",
    "Lai Châu": "Lai Châu",
    "Long An": "Long An",
    "Lào Cai": "Lào Cai",
    "Lâm Đồng": "Lâm Đồng",
    "Nam Định": "Nam Định",
    "Nghệ An": "Nghệ An",
    "Ninh Bình": "Ninh Bình",
    "Ninh Thuận": "Ninh Thuận",
    "Phú Thọ": "Phú Thọ",
    "Phú Yên": "Phú Yên",
    "Quảng Bình": "Quảng Bình",
    "Quảng Nam": "Quảng Nam",
    "Quảng Ngãi": "Quảng Ngãi",
    "Quảng Ninh": "Quảng Ninh",
    "Quảng Trị": "Quảng Trị",
    "Sóc Trăng": "Sóc Trăng",
    "Sơn La": "Sơn La",
    "TP. Hồ Chí Minh": "TP. Hồ Chí Minh",
    "Thanh Hóa": "Thanh Hóa",
    "Thái Bình": "Thái Bình",
    "Thái Nguyên": "Thái Nguyên",
    "Thừa Thiên - Huế": "Thừa Thiên - Huế",
    "Thừa Thiên-Huế": "Thừa Thiên - Huế",
    "Tiền Giang": "Tiền Giang",
    "Tp. Hồ Chí Minh": "TP. Hồ Chí Minh",
    "Trung ương": "Trung ương",
    "Trà Vinh": "Trà Vinh",
    "Tây Ninh": "Tây Ninh",
    "TỔNG SỐ": "TỔNG SỐ",
    "Vĩnh Long": "Vĩnh Long",
    "Vĩnh Phúc": "Vĩnh Phúc",
    "Vốn ngân sách NN cấp huyện": "Vốn ngân sách NN cấp huyện",
    "Vốn ngân sách NN cấp tỉnh": "Vốn ngân sách NN cấp tỉnh",
    "Vốn ngân sách NN cấp xã": "Vốn ngân sách NN cấp xã",
    "Điện Biên": "Điện Biên",
    "Đà Nẵng": "Đà Nẵng",
    "Đắk Lắk": "Đắk Lắk",
    "Đắk Lắk": "Đắk Lắk",
    "Đắk Nông": "Đắk Nông",
    "Địa phương": "Địa phương",
    "Đồng Nai": "Đồng Nai",
    "Đồng Tháp": "Đồng Tháp",
}


for pl in dfs_vdt["Phân Loại"].unique().tolist():
    assert pl in convert_phan_loai.keys(), pl


dfs_vdt["Phân Loại"] = dfs_vdt["Phân Loại"].map(convert_phan_loai)
dfs_vdt

,Phân Loại,Total-Pre-Month,Total-M,Total-YOY,YOP,YTD-YOY,MOM,Date,Month,PreMonth,PreYearMonth
0,TỔNG SỐ,79042.785,86378.37819,661294.16324,84.626662,3.309492,9.280535,2024-12-29,2024-12,2024-11,2023-12
1,Trung ương,12398.520,13826.52000,112804.14000,87.113914,-0.430428,11.517504,2024-12-29,2024-12,2024-11,2023-12
2,Bộ Giao thông Vận tải,7689.130,8465.42000,70223.83000,93.053254,-15.246546,10.095941,2024-12-29,2024-12,2024-11,2023-12
3,Bộ NN và PTNT,1049.920,1246.82000,9854.06000,83.968604,21.993481,18.753810,2024-12-29,2024-12,2024-11,2023-12
4,Bộ Y tế,151.610,179.54000,1176.74000,58.874680,28.127960,18.422268,2024-12-29,2024-12,2024-11,2023-12
...,...,...,...,...,...,...,...,...,...,...,...
5737,Khánh Hòa,NaN,85.00000,85.00000,4.476276,-18.582375,NaN,2012-01-30,2012-01,2011-12,2011-01
5738,Hưng Yên,NaN,83.60000,83.60000,7.555355,6.091371,NaN,2012-01-30,2012-01,2011-12,2011-01
5739,Ninh Thuận,NaN,66.00000,66.00000,7.581850,3.125000,NaN,2012-01-30,2012-01,2011-12,2011-01
5740,Đắk Lắk,NaN,57.00000,57.00000,5.013634,-37.362637,NaN,2012-01-30,2012-01,2011-12,2011-01
5741,Sơn La,NaN,54.50000,54.50000,4.762321,-71.673597,NaN,2012-01-30,2012-01,2011-12,2011-01

In [40]:
merge_df = pd.merge(
    left=dfs_vdt,
    right=dfs_vdt,
    left_on=["Phân Loại", "Month"],
    right_on=["Phân Loại", "PreMonth"],
    how="left",
)
merge_df["Merged_Total"] = np.where(
    merge_df["Total-Pre-Month_y"].isna(),
    merge_df["Total-M_x"],
    merge_df["Total-Pre-Month_y"],
)
merge_df = merge_df.drop(
    columns=[
        "Total-Pre-Month_y",
        "Total-M_y",
        "Total-YOY_y",
        "YOP_y",
        "YTD-YOY_y",
        "MOM_y",
        "Date_y",
        "Month_y",
        "PreMonth_y",
        "PreYearMonth_y"
    ]
)
merge_df = merge_df.rename(
    columns={
        "Total-Pre-Month_x": "Total-Pre-Month",
        "Total-M_x": "E-Total-M",
        "Total-YOY_x": "Total-YOY",
        "YOP_x": "YOP",
        "YTD-YOY_x": "YTD-YOY",
        "MOM_x": "E-MOM",
        "Date_x": "Date",
        "Month_x": "Month",
        "PreMonth_x": "PreMonth",
        "PreYearMonth_x": "PreYearMonth",
        "Merged_Total": "Total-M",
    }
)
merge_df["MOM"] = 100 * (merge_df["Total-M"] / merge_df["Total-Pre-Month"]) - 100
dfs_vdt = merge_df
merge_df[merge_df["Phân Loại"] == "TỔNG SỐ"]

,Phân Loại,Total-Pre-Month,E-Total-M,Total-YOY,YOP,YTD-YOY,E-MOM,Date,Month,PreMonth,PreYearMonth,Total-M,MOM
0,TỔNG SỐ,79042.7850,86378.37819,661294.16324,84.626662,3.309492,9.280535,2024-12-29,2024-12,2024-11,2023-12,86378.37819,9.280535
37,TỔNG SỐ,68603.2100,75880.67200,572049.82305,73.475441,2.351675,10.608049,2024-11-29,2024-11,2024-10,2023-11,79042.78500,15.217327
74,TỔNG SỐ,63869.2810,68360.46000,495926.40105,64.330561,1.824494,7.031830,2024-10-29,2024-10,2024-09,2023-10,68603.21000,7.411903
111,TỔNG SỐ,62284.3372,64371.28784,428067.94789,55.739657,1.992777,3.350683,2024-09-29,2024-09,2024-08,2023-09,63869.28100,2.544691
148,TỔNG SỐ,57074.2370,62115.05200,363097.37485,47.825462,1.978075,8.832032,2024-08-29,2024-08,2024-07,2023-08,62284.33720,9.128637
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5582,TỔNG SỐ,16666.8000,18077.20000,72993.60000,36.421735,4.005563,8.462332,2012-05-29,2012-05,2012-04,2011-05,18088.20000,8.528332
5614,TỔNG SỐ,16377.0000,17064.80000,55314.40000,27.837363,3.824554,4.199792,2012-04-30,2012-04,2012-03,2011-04,16666.80000,1.769555
5646,TỔNG SỐ,11177.3000,15106.50000,36979.10000,18.977655,1.300000,35.153391,2012-03-29,2012-03,2012-02,2011-03,16377.00000,46.520179
5677,TỔNG SỐ,10695.3000,11335.10000,22030.40000,11.549182,1.152930,5.982067,2012-02-29,2012-02,2012-01,2011-02,11177.30000,4.506652
5709,TỔNG SỐ,NaN,11244.80000,11244.80000,6.569260,-1.745802,NaN,2012-01-30,2012-01,2011-12,2011-01,10695.30000,NaN

In [41]:
merge_df = pd.merge(
    left=dfs_vdt,
    right=dfs_vdt,
    left_on=["Phân Loại", "PreYearMonth"],
    right_on=["Phân Loại", "Month"],
    how="left",
)
merge_df["M-YOY"] = 100 * (merge_df["Total-M_x"] / merge_df["Total-M_y"]) - 100
merge_df = merge_df.drop(
    columns=[
        "Total-Pre-Month_y",
        "E-Total-M_y",
        "Total-YOY_y",
        "YOP_y",
        "YTD-YOY_y",
        "E-MOM_y",
        "Date_y",
        "Month_y",
        "PreMonth_y",
        "PreYearMonth_y",
        "Total-M_y",
        "MOM_y",
    ]
)
merge_df = merge_df.rename(
    columns={
        "Total-Pre-Month_x": "Total-Pre-Month",
        "E-Total-M_x": "E-Total-M",
        "Total-YOY_x": "Total-YOY",
        "YOP_x": "YOP",
        "YTD-YOY_x": "YTD-YOY",
        "E-MOM_x": "E-MOM",
        "Date_x": "Date",
        "Month_x": "Month",
        "PreMonth_x": "PreMonth",
        "PreYearMonth_x": "PreYearMonth",
        "Total-M_x": "Total-M",
        "MOM_x": "MOM",
    }
)
dfs_vdt = merge_df
merge_df[merge_df["Phân Loại"] == "TỔNG SỐ"]

,Phân Loại,Total-Pre-Month,E-Total-M,Total-YOY,YOP,YTD-YOY,E-MOM,Date,Month,PreMonth,PreYearMonth,Total-M,MOM,M-YOY
0,TỔNG SỐ,79042.7850,86378.37819,661294.16324,84.626662,3.309492,9.280535,2024-12-29,2024-12,2024-11,2023-12,86378.37819,9.280535,11.675699
37,TỔNG SỐ,68603.2100,75880.67200,572049.82305,73.475441,2.351675,10.608049,2024-11-29,2024-11,2024-10,2023-11,79042.78500,15.217327,14.319316
74,TỔNG SỐ,63869.2810,68360.46000,495926.40105,64.330561,1.824494,7.031830,2024-10-29,2024-10,2024-09,2023-10,68603.21000,7.411903,5.274460
111,TỔNG SỐ,62284.3372,64371.28784,428067.94789,55.739657,1.992777,3.350683,2024-09-29,2024-09,2024-08,2023-09,63869.28100,2.544691,2.850637
148,TỔNG SỐ,57074.2370,62115.05200,363097.37485,47.825462,1.978075,8.832032,2024-08-29,2024-08,2024-07,2023-08,62284.33720,9.128637,2.381018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5582,TỔNG SỐ,16666.8000,18077.20000,72993.60000,36.421735,4.005563,8.462332,2012-05-29,2012-05,2012-04,2011-05,18088.20000,8.528332,NaN
5614,TỔNG SỐ,16377.0000,17064.80000,55314.40000,27.837363,3.824554,4.199792,2012-04-30,2012-04,2012-03,2011-04,16666.80000,1.769555,NaN
5646,TỔNG SỐ,11177.3000,15106.50000,36979.10000,18.977655,1.300000,35.153391,2012-03-29,2012-03,2012-02,2011-03,16377.00000,46.520179,NaN
5677,TỔNG SỐ,10695.3000,11335.10000,22030.40000,11.549182,1.152930,5.982067,2012-02-29,2012-02,2012-01,2011-02,11177.30000,4.506652,NaN
5709,TỔNG SỐ,NaN,11244.80000,11244.80000,6.569260,-1.745802,NaN,2012-01-30,2012-01,2011-12,2011-01,10695.30000,NaN,NaN

In [42]:
dfs_vdt.to_csv("../csv/vdt.csv")