In [1]:
import pandas as pd

xk_df = pd.read_csv("../csv/xk.csv")
xk_df = xk_df[
    xk_df["Ngành"].isin(
        ["TỔNG TRỊ GIÁ", "Khu vực kinh tế trong nước", "Khu vực có vốn đầu tư NN"]
    )
]
xk_df

,Unnamed: 0,Ngành,Total-M,Total-YOY,YOY,YTD-YOY,Date,Month,PreMonth,MOM
0,0,TỔNG TRỊ GIÁ,34049.626711,299625.132181,10.699933,15.363247,2024-09-29,2024-09,2024-08,-9.417597
1,1,Khu vực kinh tế trong nước,9388.747833,83466.453921,15.964694,20.727379,2024-09-29,2024-09,2024-08,-13.365525
2,2,Khu vực có vốn đầu tư NN,24660.878878,216158.678260,8.819071,13.417383,2024-09-29,2024-09,2024-08,-7.820137
41,41,TỔNG TRỊ GIÁ,37589.670481,265091.000000,14.541485,15.778097,2024-08-29,2024-08,2024-07,4.648303
42,42,Khu vực kinh tế trong nước,10837.195981,73876.607760,21.297973,21.029637,2024-08-29,2024-08,2024-07,9.806115
...,...,...,...,...,...,...,...,...,...,...
4773,4773,Khu vực kinh tế trong nước,3270.000000,7205.000000,NaN,13.200000,2014-02-28,2014-02,2014-01,-7.102273
4774,4774,Khu vực có vốn đầu tư NN,6330.000000,13855.000000,NaN,11.800000,2014-02-28,2014-02,2014-01,-6.637168
4807,4807,TỔNG TRỊ GIÁ,10300.000000,10300.000000,-10.800000,-10.800000,2014-01-29,2014-01,2013-12,NaN
4808,4808,Khu vực kinh tế trong nước,3520.000000,3520.000000,-13.800000,-13.800000,2014-01-29,2014-01,2013-12,NaN
4809,4809,Khu vực có vốn đầu tư NN,6780.000000,6780.000000,-9.200000,-9.200000,2014-01-29,2014-01,2013-12,NaN

In [2]:
import pandas as pd

nk_df = pd.read_csv("../csv/nk.csv")
nk_df = nk_df[
    nk_df["Ngành"].isin(
        ["TỔNG TRỊ GIÁ", "Khu vực kinh tế trong nước", "Khu vực có vốn đầu tư NN"]
    )
]
nk_df

,Unnamed: 0,Ngành,Total-M,Total-YOY,YOY,YTD-YOY,Date,Month,PreMonth,MOM
0,0,TỔNG TRỊ GIÁ,31758.453093,278842.181313,11.062436,17.326993,2024-09-29,2024-09,2024-08,-3.935266
1,1,Khu vực kinh tế trong nước,10938.795000,100848.495188,8.363759,18.772909,2024-09-29,2024-09,2024-08,-8.870482
2,2,Khu vực có vốn đầu tư NN,20819.658093,177993.686125,12.534919,16.523276,2024-09-29,2024-09,2024-08,-1.121788
41,41,TỔNG TRỊ GIÁ,33059.429595,246018.000000,12.377029,17.674073,2024-08-29,2024-08,2024-07,-2.191037
42,42,Khu vực kinh tế trong nước,12003.569481,89577.772549,13.222450,19.733724,2024-08-29,2024-08,2024-07,-1.610086
...,...,...,...,...,...,...,...,...,...,...
4764,4764,Khu vực kinh tế trong nước,4650.000000,9059.000000,NaN,16.800000,2014-02-28,2014-02,2014-01,1.086957
4765,4765,Khu vực có vốn đầu tư NN,6150.000000,11757.000000,NaN,17.100000,2014-02-28,2014-02,2014-01,6.034483
4801,4801,TỔNG TRỊ GIÁ,10400.000000,10400.000000,-1.900000,-1.900000,2014-01-29,2014-01,2013-12,NaN
4802,4802,Khu vực kinh tế trong nước,4600.000000,4600.000000,-2.300000,-2.300000,2014-01-29,2014-01,2013-12,NaN
4803,4803,Khu vực có vốn đầu tư NN,5800.000000,5800.000000,-1.500000,-1.500000,2014-01-29,2014-01,2013-12,NaN

In [3]:
xnk_merge = pd.merge(
    left=xk_df,
    right=nk_df,
    on=["Ngành", "Date", "Month", "PreMonth"],
    suffixes=("-XK", "-NK"),
)
xnk_merge = xnk_merge.drop(columns=["Unnamed: 0-XK", "Unnamed: 0-NK"])
xnk_merge["Thặng dự tháng"] = xnk_merge["Total-M-XK"] - xnk_merge["Total-M-NK"]
xnk_merge["Thặng dự từ đầu năm"] = xnk_merge["Total-YOY-XK"] - xnk_merge["Total-YOY-NK"]
xnk_merge["Kim ngạch xnk tháng"] = xnk_merge["Total-M-XK"] + xnk_merge["Total-M-NK"]
xnk_merge["Kim ngạch xnk từ đầu năm"] = (
    xnk_merge["Total-YOY-XK"] + xnk_merge["Total-YOY-NK"]
)
xnk_merge.head(n=5)

,Ngành,Total-M-XK,Total-YOY-XK,YOY-XK,YTD-YOY-XK,Date,Month,PreMonth,MOM-XK,Total-M-NK,Total-YOY-NK,YOY-NK,YTD-YOY-NK,MOM-NK,Thặng dự tháng,Thặng dự từ đầu năm,Kim ngạch xnk tháng,Kim ngạch xnk từ đầu năm
0,TỔNG TRỊ GIÁ,34049.626711,299625.132181,10.699933,15.363247,2024-09-29,2024-09,2024-08,-9.417597,31758.453093,278842.181313,11.062436,17.326993,-3.935266,2291.173618,20782.950868,65808.079804,578467.313494
1,Khu vực kinh tế trong nước,9388.747833,83466.453921,15.964694,20.727379,2024-09-29,2024-09,2024-08,-13.365525,10938.795000,100848.495188,8.363759,18.772909,-8.870482,-1550.047167,-17382.041267,20327.542833,184314.949109
2,Khu vực có vốn đầu tư NN,24660.878878,216158.678260,8.819071,13.417383,2024-09-29,2024-09,2024-08,-7.820137,20819.658093,177993.686125,12.534919,16.523276,-1.121788,3841.220785,38164.992135,45480.536971,394152.364385
3,TỔNG TRỊ GIÁ,37589.670481,265091.000000,14.541485,15.778097,2024-08-29,2024-08,2024-07,4.648303,33059.429595,246018.000000,12.377029,17.674073,-2.191037,4530.240886,19073.000000,70649.100076,511109.000000
4,Khu vực kinh tế trong nước,10837.195981,73876.607760,21.297973,21.029637,2024-08-29,2024-08,2024-07,9.806115,12003.569481,89577.772549,13.222450,19.733724,-1.610086,-1166.373500,-15701.164789,22840.765462,163454.380309

In [4]:
xnk_merge["Date"] = pd.to_datetime(xnk_merge["Date"], dayfirst=False)
xnk_merge["PreMonth"] = (
        xnk_merge["Date"]
        .apply(
            lambda x: (
                x.replace(month=x.month - 1, day=1)
                if x.month > 1
                else x.replace(year=x.year - 1, month=12, day=1)
            )
        )
        .dt.strftime("%Y-%m")
    )
xnk_merge["PreYearMonth"] = (
    xnk_merge["Date"]
    .apply(lambda x: x.replace(year=x.year - 1, day=1))
    .dt.strftime("%Y-%m")
)
xnk_merge.head(n=5)

,Ngành,Total-M-XK,Total-YOY-XK,YOY-XK,YTD-YOY-XK,Date,Month,PreMonth,MOM-XK,Total-M-NK,Total-YOY-NK,YOY-NK,YTD-YOY-NK,MOM-NK,Thặng dự tháng,Thặng dự từ đầu năm,Kim ngạch xnk tháng,Kim ngạch xnk từ đầu năm,PreYearMonth
0,TỔNG TRỊ GIÁ,34049.626711,299625.132181,10.699933,15.363247,2024-09-29,2024-09,2024-08,-9.417597,31758.453093,278842.181313,11.062436,17.326993,-3.935266,2291.173618,20782.950868,65808.079804,578467.313494,2023-09
1,Khu vực kinh tế trong nước,9388.747833,83466.453921,15.964694,20.727379,2024-09-29,2024-09,2024-08,-13.365525,10938.795000,100848.495188,8.363759,18.772909,-8.870482,-1550.047167,-17382.041267,20327.542833,184314.949109,2023-09
2,Khu vực có vốn đầu tư NN,24660.878878,216158.678260,8.819071,13.417383,2024-09-29,2024-09,2024-08,-7.820137,20819.658093,177993.686125,12.534919,16.523276,-1.121788,3841.220785,38164.992135,45480.536971,394152.364385,2023-09
3,TỔNG TRỊ GIÁ,37589.670481,265091.000000,14.541485,15.778097,2024-08-29,2024-08,2024-07,4.648303,33059.429595,246018.000000,12.377029,17.674073,-2.191037,4530.240886,19073.000000,70649.100076,511109.000000,2023-08
4,Khu vực kinh tế trong nước,10837.195981,73876.607760,21.297973,21.029637,2024-08-29,2024-08,2024-07,9.806115,12003.569481,89577.772549,13.222450,19.733724,-1.610086,-1166.373500,-15701.164789,22840.765462,163454.380309,2023-08

In [5]:
merge_df = pd.merge(
    left=xnk_merge,
    right=xnk_merge,
    left_on=["Ngành", "PreMonth"],
    right_on=["Ngành", "Month"],
    how="left",
)

merge_df["Thặng dự tháng - MOM"] = (
    100 * (merge_df["Thặng dự tháng_x"] / merge_df["Thặng dự tháng_y"]) - 100
)
# merge_df["Thặng dự từ đầu năm - MOM"] = (
#     100 * (merge_df["Thặng dự từ đầu năm_x"] / merge_df["Thặng dự từ đầu năm_y"]) - 100
# )
merge_df["Kim ngạch xnk tháng - MOM"] = (
    100 * (merge_df["Kim ngạch xnk tháng_x"] / merge_df["Kim ngạch xnk tháng_y"]) - 100
)
# merge_df["Kim ngạch xnk từ đầu năm - MOM"] = (
#     100
#     * (merge_df["Kim ngạch xnk từ đầu năm_x"] / merge_df["Kim ngạch xnk từ đầu năm_y"])
#     - 100
# )

merge_df = merge_df.drop(
    columns=[
        "Total-M-XK_y",
        "Total-YOY-XK_y",
        "YOY-XK_y",
        "YTD-YOY-XK_y",
        "Date_y",
        "Month_y",
        "PreMonth_y",
        "MOM-XK_y",
        "Total-M-NK_y",
        "Total-YOY-NK_y",
        "YOY-NK_y",
        "YTD-YOY-NK_y",
        "MOM-NK_y",
        "Thặng dự tháng_y",
        "Thặng dự từ đầu năm_y",
        "Kim ngạch xnk tháng_y",
        "Kim ngạch xnk từ đầu năm_y",
        "PreYearMonth_y",
    ]
)
merge_df = merge_df.rename(
    columns={
        "Total-M-XK_x": "Total-M-XK",
        "Total-YOY-XK_x": "Total-YOY-XK",
        "YOY-XK_x": "YOY-XK",
        "YTD-YOY-XK_x": "YTD-YOY-XK",
        "Date_x": "Date",
        "Month_x": "Month",
        "PreMonth_x": "PreMonth",
        "MOM-XK_x": "MOM-XK",
        "Total-M-NK_x": "Total-M-NK",
        "Total-YOY-NK_x": "Total-YOY-NK",
        "YOY-NK_x": "YOY-NK",
        "YTD-YOY-NK_x": "YTD-YOY-NK",
        "MOM-NK_x": "MOM-NK",
        "Thặng dự tháng_x": "Thặng dự tháng",
        "Thặng dự từ đầu năm_x": "Thặng dự từ đầu năm",
        "Kim ngạch xnk tháng_x": "Kim ngạch xnk tháng",
        "Kim ngạch xnk từ đầu năm_x": "Kim ngạch xnk từ đầu năm",
        "PreYearMonth_x": "PreYearMonth",
    }
)
xnk_merge = merge_df
merge_df[merge_df["Ngành"] == "TỔNG TRỊ GIÁ"].columns

Index(['Ngành', 'Total-M-XK', 'Total-YOY-XK', 'YOY-XK', 'YTD-YOY-XK', 'Date',
       'Month', 'PreMonth', 'MOM-XK', 'Total-M-NK', 'Total-YOY-NK', 'YOY-NK',
       'YTD-YOY-NK', 'MOM-NK', 'Thặng dự tháng', 'Thặng dự từ đầu năm',
       'Kim ngạch xnk tháng', 'Kim ngạch xnk từ đầu năm', 'PreYearMonth',
       'Thặng dự tháng - MOM', 'Kim ngạch xnk tháng - MOM'],
      dtype='object')

In [6]:
merge_df = pd.merge(
    left=xnk_merge,
    right=xnk_merge,
    left_on=["Ngành", "PreYearMonth"],
    right_on=["Ngành", "Month"],
    how="left",
)

merge_df["Thặng dự tháng - YOY"] = (
    100 * (merge_df["Thặng dự tháng_x"] / merge_df["Thặng dự tháng_y"]) - 100
)
merge_df["Thặng dự từ đầu năm - YOY"] = (
    100 * (merge_df["Thặng dự từ đầu năm_x"] / merge_df["Thặng dự từ đầu năm_y"]) - 100
)
merge_df["Kim ngạch xnk tháng - YOY"] = (
    100 * (merge_df["Kim ngạch xnk tháng_x"] / merge_df["Kim ngạch xnk tháng_y"]) - 100
)
merge_df["Kim ngạch xnk từ đầu năm - YOY"] = (
    100
    * (merge_df["Kim ngạch xnk từ đầu năm_x"] / merge_df["Kim ngạch xnk từ đầu năm_y"])
    - 100
)

merge_df = merge_df.drop(
    columns=[
        "Total-M-XK_y",
        "Total-YOY-XK_y",
        "YOY-XK_y",
        "YTD-YOY-XK_y",
        "Date_y",
        "Month_y",
        "PreMonth_y",
        "MOM-XK_y",
        "Total-M-NK_y",
        "Total-YOY-NK_y",
        "YOY-NK_y",
        "YTD-YOY-NK_y",
        "MOM-NK_y",
        "Thặng dự tháng_y",
        "Thặng dự từ đầu năm_y",
        "Kim ngạch xnk tháng_y",
        "Kim ngạch xnk từ đầu năm_y",
        "PreYearMonth_y",
        "Thặng dự tháng - MOM_y",
        "Kim ngạch xnk tháng - MOM_y",
    ]
)
merge_df = merge_df.rename(
    columns={
        "Total-M-XK_x": "Total-M-XK",
        "Total-YOY-XK_x": "Total-YOY-XK",
        "YOY-XK_x": "YOY-XK",
        "YTD-YOY-XK_x": "YTD-YOY-XK",
        "Date_x": "Date",
        "Month_x": "Month",
        "PreMonth_x": "PreMonth",
        "MOM-XK_x": "MOM-XK",
        "Total-M-NK_x": "Total-M-NK",
        "Total-YOY-NK_x": "Total-YOY-NK",
        "YOY-NK_x": "YOY-NK",
        "YTD-YOY-NK_x": "YTD-YOY-NK",
        "MOM-NK_x": "MOM-NK",
        "Thặng dự tháng_x": "Thặng dự tháng",
        "Thặng dự từ đầu năm_x": "Thặng dự từ đầu năm",
        "Kim ngạch xnk tháng_x": "Kim ngạch xnk tháng",
        "Kim ngạch xnk từ đầu năm_x": "Kim ngạch xnk từ đầu năm",
        "PreYearMonth_x": "PreYearMonth",
        "Thặng dự tháng - MOM_x": "Thặng dự tháng - MOM",
        "Kim ngạch xnk tháng - MOM_x": "Kim ngạch xnk tháng - MOM",
    }
)
xnk_merge = merge_df
merge_df[merge_df["Ngành"] == "TỔNG TRỊ GIÁ"].columns

Index(['Ngành', 'Total-M-XK', 'Total-YOY-XK', 'YOY-XK', 'YTD-YOY-XK', 'Date',
       'Month', 'PreMonth', 'MOM-XK', 'Total-M-NK', 'Total-YOY-NK', 'YOY-NK',
       'YTD-YOY-NK', 'MOM-NK', 'Thặng dự tháng', 'Thặng dự từ đầu năm',
       'Kim ngạch xnk tháng', 'Kim ngạch xnk từ đầu năm', 'PreYearMonth',
       'Thặng dự tháng - MOM', 'Kim ngạch xnk tháng - MOM',
       'Thặng dự tháng - YOY', 'Thặng dự từ đầu năm - YOY',
       'Kim ngạch xnk tháng - YOY', 'Kim ngạch xnk từ đầu năm - YOY'],
      dtype='object')

In [7]:
xnk_merge.to_csv("../csv/xnk.csv")